[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/zincwork-tagging"
  to = "/zincwork-tagging"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/zincwork-tagging"
  status = 302
  force = true
